myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.Index, name='index'),
    path('login/',views.Login, name='login'),
    path('inicio/',views.inicio, name='inicio'),
    path('alumnos/',views.Lista_alumnos, name='Lista'),
    path('Grupos/',views.Grupos, name='grupos'),
    path('generar-pdf/',views.generar_pdf, name='pdf'),
    path('docente/',views.maestro, name='docente'),
    path('<str:rol>/logout/',views.signout, name='logout'),
    path('pdf-profe/',views.pdf_profe),
    path('admin-usuario/',views.crud_usuarios,name='crud-usuarios'),
    path('admin-grupo/',views.crud_grupo,name='crud-grupo'),
    path('admin-alumnos/', views.crud_alumno, name='admin-alumno'),
    path('<str:pag>/añadir-alumno/', views.crud_alumno_añadir, name='crud-alumno-añadir'),
    path('admin-docente/', views.crud_docente, name='admin-docente'),
    path('<str:pag>/añadir/', views.crud_docente_añadir, name='crud_docente_añadir'),
    path("pagos/", views.lista_pagos, name="lista_pagos"),
    path('pdf-factura/',views.pdf_factura),
    path('informacion/', views.informacion),
    path('p/',views.crendencial),
    path('inicio-admin/', views.inicio_admin, name='inicio-admin')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.core.validators import FileExtensionValidator
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User, AbstractUser
from django.contrib.auth.hashers import make_password, check_password
from datetime import date, timedelta
from django.db.models.signals import post_save
from django.dispatch import receiver
import calendar

# Create your models here.
#

from django.db import models

class profesor(models.Model):
    nombre_profesor = models.CharField(max_length=200)
    apellidos_profesor = models.CharField(max_length=200)
    curp = models.FileField(upload_to='documentos/', validators=[FileExtensionValidator(allowed_extensions=['pdf'])])
    comprobante_domicilio = models.FileField(upload_to='documentos/', validators=[FileExtensionValidator(allowed_extensions=['pdf'])])
    cedula_profesional = models.FileField(upload_to='documentos/', validators=[FileExtensionValidator(allowed_extensions=['pdf'])])
    identificacion = models.FileField(upload_to='documentos/', validators=[FileExtensionValidator(allowed_extensions=['pdf'])])
    telefono = models.CharField(max_length=15)
    edad = models.PositiveIntegerField()
    correo_electronico = models.EmailField()
    fecha_registro = models.DateTimeField(auto_now_add=True)
    foto = models.ImageField(upload_to='fotos/', validators=[FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])],default='fotos/default.jpg')

    def clean(self):
        existe = profesor.objects.filter(
            nombre_profesor = self.nombre_profesor,
            telefono = self.telefono,
            correo_electronico = self.correo_electronico
        ).exclude(pk=self.pk).exists()

        if existe:
            raise ValidationError("El profesor ya se encuentra registrado")

    def __str__(self):
        return f'{self.nombre_profesor} {self.apellidos_profesor}'


class grupo(models.Model):
    nombre_grupo = models.CharField(max_length=2)
    grado = models.PositiveSmallIntegerField(choices=[(1, '1°'), (2, '2°'), (3, '3°')])
    turno = models.CharField(max_length=20, choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino')])
    profesor = models.ForeignKey(profesor, on_delete=models.SET_NULL, null=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.nombre_grupo} - {self.get_grado_display()} - {self.turno}"

class alumno(models.Model):
    nombre_alumno = models.CharField(max_length=100)
    apellidos_alumno = models.CharField(max_length=100)
    curp = models.CharField(max_length=18, unique=True)
    fecha_nacimiento = models.DateField()
    direccion = models.TextField()
    fecha_registro = models.DateTimeField(auto_now_add=True)
    foto = models.ImageField(upload_to="alumnos/fotos/", blank=True, null=True)
    acta_nacimiento = models.FileField(upload_to="alumnos/actas/", blank=True, null=True)
    comprobante_domicilio = models.FileField(upload_to="alumnos/comprobantes/", blank=True, null=True)
    tutores = models.ManyToManyField("Tutor", related_name="alumnos")
    grupo = models.ForeignKey(grupo, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.nombre_alumno} {self.apellidos_alumno}"

class tutor(models.Model):
    RELACION_CHOICES = [
        ('PADRE', 'Padre'),
        ('MADRE', 'Madre'),
        ('ABUELO', 'Abuelo/Abuela'),
        ('TUTOR', 'Tutor Legal'),
        ('OTRO', 'Otro'),
    ]

    nombre_tutor = models.CharField(max_length=100)
    apellidos_tutor = models.CharField(max_length=100)
    telefono = models.CharField(max_length=15)
    email = models.EmailField()
    relacion = models.CharField(max_length=10, choices=RELACION_CHOICES)
    foto = models.ImageField(upload_to="tutores/fotos/", blank=True, null=True)
    ine = models.FileField(upload_to="tutores/ine/", blank=True, null=True)
    comprobante_domicilio = models.FileField(upload_to="tutores/comprobantes/", blank=True, null=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['nombre_tutor', 'apellidos_tutor', 'telefono', 'email'],
                name='unique_tutor'
            )
        ]

    def __str__(self):
        return f"{self.nombre_tutor} ({self.relacion})"


class colegiatura(models.Model):
    METODO_CHOICES = [
        ('EFECTIVO', 'Efectivo'),
        ('TRANSFERENCIA', 'Transferencia Bancaria'),
        ('TARJETA', 'Tarjeta de Crédito/Débito'),
    ]

    ESTADO_CHOICES = [
        ('PENDIENTE', 'Pendiente'),
        ('PAGADO', 'Pagado'),
        ('VENCIDO', 'Vencido'),
    ]

    alumno = models.ForeignKey(alumno, on_delete=models.CASCADE, related_name="pagos")
    monto = models.DecimalField(max_digits=10, decimal_places=2, default=2000.00)
    fecha_pago = models.DateField()
    mes = models.CharField(max_length=20)
    metodo = models.CharField(max_length=20, choices=METODO_CHOICES, default='EFECTIVO')
    referencia = models.CharField(max_length=50, default='Pago de colegiatura mensual')
    estado = models.CharField(max_length=10, choices=ESTADO_CHOICES, default='PENDIENTE')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.mes} - {self.alumno} ({self.estado})"

@receiver(post_save, sender=colegiatura)
def generar_siguiente_mes(sender, instance, created, **kwargs):
    if instance.estado == "PAGADO" or instance.estado == "VENCIDO":
        fecha_actual = instance.fecha_pago
        siguiente_mes = fecha_actual.month + 1
        siguiente_anio = fecha_actual.year

        if siguiente_mes > 12:
            siguiente_mes = 1
            siguiente_anio += 1

        MESES_ES = {
            1: "Enero", 2: "Febrero", 3: "Marzo", 4: "Abril",
            5: "Mayo", 6: "Junio", 7: "Julio", 8: "Agosto",
            9: "Septiembre", 10: "Octubre", 11: "Noviembre", 12: "Diciembre",
        }

        mes_str = f"{MESES_ES[siguiente_mes]} {siguiente_anio}"

        pagos_en_anio = colegiatura.objects.filter(
            alumno=instance.alumno,
            fecha_pago__year=siguiente_anio
        ).count()

        if pagos_en_anio >= 12:
            return  

        existe = colegiatura.objects.filter(
            alumno=instance.alumno,
            mes=mes_str
        ).exists()

        if not existe:
            colegiatura.objects.create(
                alumno=instance.alumno,
                monto=instance.monto,
                fecha_pago=fecha_actual + timedelta(days=30),
                mes=mes_str,
                metodo="EFECTIVO",
                referencia="Pago de Colegiatura",
                estado="PENDIENTE"
            )


class usuario(AbstractUser):
    foto = models.ImageField(upload_to='fotos/', validators=[FileExtensionValidator(['jpg', 'png', 'jpeg'])])
    telefono = models.CharField(max_length=15, default=123456789012345)
    

myapp/templates/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>ola admin</h1>
    <a href="logout/">
                    
                        <span>Salir</span>
                    </a>
</body>
</html>

myapp/templates/colegiatura.html
{% extends 'layouts/slider.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'styles/colegiatura.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
{% endblock %}
{% block content-slider %}
<main id="contenido">
    {% if mensaje %}
        <div id="alerta-ok" class="alerta ok">
            <div>
                <p>Exito</p>
                <p>{{ mensaje }}</p>
            </div>
            <button class="cerrar" onclick="cerrarAlerta('alerta-error')">&times;</button>
        </div>
    {% endif %}
    {% if pago_seleccionado == None %}
    <div class="cabeza">
        <h2>Pagar colegiatura</h2>
        {% if formulario.non_field_errors %}
        {% for error in formulario.non_field_errors %}
        <div class="contenido">
            <p class="titulo">Error</p>
            <ul>
                <li>{{error}}</li>
            </ul>
        </div>
        {% endfor %}
        {% endif %}
        <form action="" method="post" class="form-pago">
            {% csrf_token %}
            <div>
            <label>Alumno</label>
                <div class="alumno-inputs">
                <input type="text" id="igiak_alumno_nombre" class="input campos" readonly placeholder="Selecciona un alumno">
                <input type="hidden" name="alumno" id="igiak_alumno_id">
                <button type="button" id="igiak_btnBuscarAlumno">Buscar</button>
                </div>
            </div>
            <div>
                <label>{{ formulario.monto.label }}</label>
                {{ formulario.monto }}
            </div>
            <div>
                <label>{{ formulario.fecha_pago.label }}</label>
                {{ formulario.fecha_pago }}
            </div>
            <div>
                <label>{{ formulario.metodo.label }}</label>
                {{ formulario.metodo }}
            </div>
            <div>
                <label>{{ formulario.referencia.label }}</label>
                {{ formulario.referencia }}
            </div>
            <div>
                <label>{{ formulario.estado.label }}</label>
                {{ formulario.estado }}
            </div>
            <button>Registrar</button>
        </form>
        <dialog id="igiak_modalAlumno" class="modal">
            <form method="dialog" class="modal-content">
                <h3>Buscar alumno</h3>
                <div class="filtro">
                    <div class="filtro-container">
                        <button type="button" class="btn-filtros" id="igiak_btnToggleFiltros">Filtros</button>
                        <button type="button" class="btn-filtros" id="igiak_btnResetFiltros">Reestablecer</button>
                        <div class="lista-filtros" id="igiak_listaFiltros" style="display:none;">
                            <label><input type="radio" name="igiak_filtro" value="0" checked> ID</label>
                            <label><input type="radio" name="igiak_filtro" value="1"> Alumno</label>
                            <label><input type="radio" name="igiak_filtro" value="2" > Grupo</label>
                        </div>
                        <input type="search" class="buscador-alumno" id="igiak_buscador" placeholder="Buscar..." />
                    </div>
                </div>
                <table class="tabla-alumnos" id="igiak_tablaAlumnos">
                    <tbody id="igiak_tbodyAlumnos">
                        {% for a in alumnos %}
                            <tr class="fila-alumno" data-id="{{ a.id }}" data-nombre="{{ a.nombre_alumno }} {{ a.apellidos_alumno }}" data-grupo="{{ a.grupo }}">
                                <td>{{ a.id }}</td>
                                <td>{{ a.nombre_alumno }} {{ a.apellidos_alumno }}</td>
                                <td>{{ a.grupo }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <menu>
                    <button value="cancel">Cerrar</button>
                </menu>
            </form>
        </dialog>
    </div>
    {% endif %}
    {% if pago_seleccionado %}
    <div class="cabeza">
        <h2>Pagar {{ pago_seleccionado.mes }} - {{ pago_seleccionado.alumno }}</h2>
        {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <div class="contenido">
            <p class="titulo">Error</p>
            <ul>
                <li>{{error}}</li>
            </ul>
        </div>
        {% endfor %}
        {% endif %}
        <form method="post" class="form-pago">
            {% csrf_token %}
            {% if form.errors %} <div style="color:red;"> {{ form.errors }} </div> {% endif %}
            <input type="hidden" name="pago_id" value="{{ pago_seleccionado.id }}">
            {{form}}
            <button type="submit">Confirmar Pago</button>
        </form>
    </div>
    {% endif %}
    <div class="filtro">
        <div class="filtro-container">
            <button class="btn-filtros" onclick="toggleFiltrosGenerales()">Filtros</button>
            <button onclick="resetFiltrosGenerales()" class="btn-filtros">Reestablecer</button>
            <div class="lista-filtros" id="listaFiltros" style="display:none;">
                <label><input type="radio" name="filtro" value="0" checked> ID</label>
                <label><input type="radio" name="filtro" value="1"> Alumno</label>
                <label><input type="radio" name="filtro" value="2"> Mes</label>
                <label><input type="radio" name="filtro" value="3"> Monto</label>
                <label><input type="radio" name="filtro" value="4"> Fecha de Pago</label>
                <label><input type="radio" name="filtro" value="5"> Método</label>
                <label><input type="radio" name="filtro" value="6"> Referencia</label>
                <label><input type="radio" name="filtro" value="7"> Estado</label>
            </div>
            <input type="search" class="buscador" id="buscador" placeholder="Buscar por ID..." onkeyup="aplicarFiltrosGenerales()">
        </div>
    </div>
    <div class="filtro-fechas">
        <label>Desde:</label>
        <input type="date" id="desde">
        <label>Hasta:</label>
        <input type="date" id="hasta">
        <button onclick="aplicarFiltrosGenerales()" class="acciones-filtros">Filtrar</button>
    </div>
    <h2>Lista de Pagos</h2>
    <table class="tabla">
        <thead>
            <tr>
                <th>ID</th>
                <th>Alumno</th>
                <th>Mes</th>
                <th>Monto</th>
                <th>Fecha de Pago</th>
                <th>Método</th>
                <th>Referencia</th>
                <th>Estado</th>
                <th>Pagar</th>
                <th>Accion</th>
            </tr>
        </thead>
        <tbody>
            {% for pago in pagos %}
            <tr>
                <td>{{pago.id}}</td>
                <td>{{ pago.alumno }}</td>
                <td>{{ pago.mes }}</td>
                <td>{{ pago.monto }}</td>
                <td>{{ pago.fecha_pago }}</td>
                <td>{{ pago.metodo }}</td>
                <td>{{ pago.referencia }}</td>
                <td {% if pago.estado == "PENDIENTE" %} style="background-color: #e36b77;" 
                {% elif pago.estado == 'VENCIDO' %} style="background-color: #ecb865;"
                {% elif pago.estado == "PAGADO" %} style="background-color: #58e25f;" 
                {% endif %}>{{ pago.estado }}
                </td>
                <td>
                    {% if pago.estado == "PENDIENTE" %}
                    <a href="?pago_id={{ pago.id }}" class="pagar">
                        <img src="{% static '/imagenes/money.svg'%}" alt="Colegiaturas" class="pagar">
                    </a>
                    {% else %}
                    ---
                    {% endif %}
                </td>
                <td>
                    <input type="hidden" id="colegiatura_id_{{pago.id}}" value="{{pago.id}}">
                    <a href="#" onclick="PDF({{pago.id}}); return false;">
                        <i class="fa-regular fa-file-pdf"></i>
                    </a>
                    <i class="fa-regular fa-envelope"></i>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="pagination" id="paginacion"></div>
</main>
<script src="{% static 'javascript/colegiatura.js' %}"></script>
<script src="{% static 'javascript/busqueda.js' %}"></script>
<script>
    function cerrarAlerta(id) {
    const alerta = document.getElementById(id);
    if (alerta) {
        alerta.style.opacity = '0';
        setTimeout(() => alerta.remove(), 500);
    }
}

window.addEventListener('DOMContentLoaded', () => {
    setTimeout(() => cerrarAlerta('alerta-error'), 4000);
    setTimeout(() => cerrarAlerta('alerta-ok'), 4000);
});
function PDF(id){
    const url = `/pdf-factura/?colegiatura_id=${encodeURIComponent(id)}`;
    window.open(url,'_blank');
}
</script>
{% endblock %}

myapp/templates/crear.html
{% extends 'layouts/slider.html' %}
{% block content-slider %}
    <main id="contenido">
        {{formulario}}
    </main>
{% endblock %}

myapp/templates/descarga_pdf.html
{% extends 'layouts/pdf.html' %}
{% load static %}
{% block content %}
<div id="contenido-pdf">
        <div class="logo">
            <img src="{% static '/imagenes/logopag.png' %}" alt="EduControl Logo">
        </div>

        <h1>Listado de Alumnos</h1>
        <div class="info-grupo">
            Grupo: {{ request.GET.grupo }} &nbsp;|&nbsp; Turno: {{ request.GET.turno }} |&nbsp;
            {% for alumnos in alumno %}
            Profesor: {{ alumnos.grupo.profesor }}
            {% endfor %}
        </div>

        <table>
            <tr>
                <th class="numero">No.</th>
                <th class="nombre">Alumno</th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
            {% for alumnos in alumno %}
            <tr>
                <td class="numero">{{ forloop.counter }}</td>
                <td class="nombre">{{ alumnos.nombre_alumno }} {{ alumnos.apellido_alumno }}</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            {% endfor %}
        </table>

        <div class="footer">
            Fecha de generación: {{ now|date:"d/m/Y H:i" }}<br>
            Documento generado automáticamente por EduControl
        </div>
    </div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>
<script>
    const grupo = '{{request.GET.grupo}}'
    const turno = '{{request.GET.turno}}'
    window.onload = function() {
        const elemento = document.getElementById('contenido-pdf');
        const opciones = {
            margin: 0,
            filename: `Grupo-${grupo}-${turno}.pdf`,
            image: { type: 'jpeg', quality: 0.98 },
            html2canvas: { scale: 2 },
            jsPDF: { unit: 'in', format: 'letter', orientation: 'landscape' }
        };
    html2pdf().set(opciones).from(elemento).save().then(() => {
        setTimeout(() => {
            window.close();
        }, 10);
    });
};
</script>
{% endblock %}

myapp/templates/factura-email.html
<!DOCTYPE html>
{% load static %}
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Factura</title>
    <link rel="stylesheet" href="{% static 'styles/factura.css' %}">
</head>

<body>
<div class="invoice" id="contenido-pdf">

    <header class="invoice-header">
        <div class="hero-background"></div>
    </header>

    <div class="invoice-content">

        <div class="row">
            <div class="col-left"></div>
            <div class="header-content">
                <div class="logo">
                    <img src="https://i.postimg.cc/yk3CG0ms/educontrol.png" alt="">
                    <h2>Educontrol</h2>
                </div>
            </div>
        </div>

        <section class="data-client">
            <h3>Datos del Cliente</h3>
            <ul class="client">
                <li><strong>Alumno: </strong>{{ alumno.nombre_alumno }} {{ alumno.apellidos_alumno }}</li>
                {% for tutor in tutores %}
                    <li><strong>Tutor: </strong>{{ tutor.nombre_tutor }} {{ tutor.apellidos_ptutor }}</li>
                    <li><strong>Email: </strong>{{ tutor.email }}</li>
                    <li><strong>Teléfono: </strong>{{ tutor.telefono }}</li>
                {% endfor %}
            </ul>
        </section>

        <section class="date-number">
            <p><strong>Número: </strong>{{ colegiatura.id }}</p>
            <p><strong>Fecha: </strong>{{ colegiatura.fecha_pago|date:"d/m/Y" }}</p>
        </section>

        <table class="table">
            <thead>
                <tr>
                    <th>Cantidad</th>
                    <th>Concepto</th>
                    <th>Descripción</th>
                    <th>Importe</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>Pago de colegiatura mensual de {{ colegiatura.mes }}</td>
                    <td>Alumno: {{ alumno.nombre_alumno }} {{ alumno.apellidos_alumno }}</td>
                    <td>$ {{ colegiatura.monto }}</td>
                </tr>
            </tbody>
        </table>

        <div class="summary">
            <p><strong>Forma de pago: </strong>{{ colegiatura.metodo }}</p>
        </div>

        <section class="totals">
            <ul class="total">
                <li><strong>Subtotal: </strong>$ {{ colegiatura.monto }}</li>
                <li><strong>IVA: </strong>$ 0.00</li>
                <li><strong>Total: </strong>$ {{ colegiatura.monto }}</li>
            </ul>
        </section>

        <footer class="invoice-footer">
            <div class="company">
                <div class="signature">
                    <hr class="line">
                    <p>Firma y sello</p>
                </div>
                <ul class="bussines-info">
                    <li>EduControl</li>
                    <li>Email: educontrol@hotmail.com</li>
                    <li>Teléfono: 32040234324</li>
                </ul>
            </div>
        </footer>
        <div class="footer-background"></div>
    </div>
</div>
</body>
</html>

myapp/templates/informacion.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Informacion</title>
    <link rel="stylesheet" href="{% static 'styles/informacion.css' %}">
</head>

<body>
    <div class="encabezado">
        <a href="{% url 'Lista' %}" class="btn-volver">⟵ Volver</a>
    </div>
    <div class="ficha">
        <div class="alumno">
            <h3 class="barra">Datos Generales del alumno</h3>
            <div class="datos">
                <div class="imagen">
                    {% if alumno.foto %}
                        <img src="{{ alumno.foto.url }}" alt="Foto Alumno" class="foto">
                    {% endif %}
                </div>
                <div class="datos-personales">
                    <div>
                        <label class="label">Nombre(s): </label>
                        <input type="text" disabled value="{{ alumno.nombre_alumno }}" class="input">
                    </div>
                    <div>
                        <label class="label">Apellidos: </label>
                        <input type="text" disabled value="{{ alumno.apellidos_alumno }}" class="input">
                    </div>
                    <div>
                        <label class="label">CURP: </label>
                        <input type="text" disabled value="{{ alumno.curp }}" class="input">
                    </div>
                    <div>
                        <label class="label">Fecha de Nacimiento: </label>
                        <input type="text" disabled value="{{ alumno.fecha_nacimiento }}" class="input">
                    </div>
                    <div>
                        <label class="label">Direccion: </label>
                        <input type="text" disabled value="{{ alumno.direccion }}" class="inputs">
                    </div>
                    <div>
                        <label class="label">Grupo: </label>
                        <input type="text" disabled value="{{ grupo.nombre_grupo }} - {{ grupo.get_grado_display }}" class="inputs">
                    </div>
                    <div>
                        <label class="label">Turno: </label>
                        <input type="text" disabled value="{{ grupo.turno }}" class="inputs">
                    </div>
                    <div>
                        <label class="label">Acta de Nacimiento: </label>
                        {% if alumno.acta_nacimiento %}
                            <a href="{{ alumno.acta_nacimiento.url }}" target="_blank" class="archivo">Ver documento</a>
                        {% endif %}
                    </div>
                    <div>
                        <label class="label">Comprobante de domicilio: </label>
                        {% if alumno.comprobante_domicilio %}
                            <a href="{{ alumno.comprobante_domicilio.url }}" target="_blank" class="archivo">Ver documento</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div class="tutor">
            <h3 class="barra">Datos del tutor(es)</h3>
            {% for tutor in tutores %}
            <div class="datos">
                <div class="imagen">
                    {% if tutor.foto %}
                        <img src="{{ tutor.foto.url }}" alt="Foto Tutor" class="foto">
                    {% endif %}
                </div>
                <div class="datos-personales">
                    <div>
                        <label class="label">Nombre Completo: </label>
                        <input type="text" disabled value="{{ tutor.nombre_tutor }} {{ tutor.apellidos_tutor }}" class="input">
                    </div>
                    <div>
                        <label class="label">Telefono: </label>
                        <input type="text" disabled value="{{ tutor.telefono }}" class="input">
                    </div>
                    <div>
                        <label class="label">Correo Electronico: </label>
                        <input type="text" disabled value="{{ tutor.email }}" class="input">
                    </div>
                    <div>
                        <label class="label">Relacion con el alumno: </label>
                        <input type="text" disabled value="{{ tutor.get_relacion_display }}" class="input">
                    </div>
                    <div>
                        <label class="label">INE: </label>
                        {% if tutor.ine %}
                            <a href="{{ tutor.ine.url }}" target="_blank" class="archivo">Ver documento</a>
                        {% endif %}
                    </div>
                    <div>
                        <label class="label">Comprobante de domicilio: </label>
                        {% if tutor.comprobante_domicilio %}
                            <a href="{{ tutor.comprobante_domicilio.url }}" target="_blank" class="archivo">Ver documento</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% empty %}
                <p>No hay tutores registrados</p>
            {% endfor %}
        </div>
    </div>
</body>

</html>

myapp/templates/inicio.html
{% extends 'layouts/slider.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'styles/inicio.css' %}">
{% endblock %}
{% block content-slider %}
<main id="contenido">
    <div class="perfil">
        <div class="imagen-perfil">
            {% if request.user.is_authenticated and request.user.foto %}
            <img src="{{ request.user.foto.url }}" alt="Foto de perfil"  class="imagen" title="{{request.user.username}}">
            {% endif %}
        </div>
        <div class="usuario-perfil">
            {% if request.user.is_authenticated and request.user.username %}
                <h3>¡Bienvenido de nuevo, {{request.user.username}}!</h3>
            {% endif %}
        </div>
    </div>
</main>
{% endblock %}